### ISSUE TITLE
Classify bad data in commit data

### ISSUE THREAD

**Issue by JihoJu** [jiahho/Commit-Message-Corrector#2]
commit message data 중 bad data 라고 결정된 데이터를 분류

**Comment by khj1030** [comment]
의미없는 commit 기준
1. 숫자만 있는 경우
2. 빈 commit인 경우
3. '.'만 있는 commit (문자 length가 1인 경우)

**Comment by khj1030** [comment]
의미없는 commit 기준

1. 숫자만 있는 경우
2. 빈 commit인 경우
3. '.'만 있는 commit (문자 length가 1인 경우)
